# Generated by Django 2.2.3 on 2020-01-03 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('socket', models.CharField(max_length=100)),
                ('multithread_score', models.IntegerField(verbose_name='m_score')),
                ('singlethreaded_score', models.IntegerField(verbose_name='s_score')),
                ('samples', models.IntegerField()),
                ('release_date', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
        ),
    ]
