# Generated by Django 2.2.3 on 2020-01-03 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200103_1712'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cpu',
            old_name='multhithreading',
            new_name='multithreading',
        ),
    ]
