# Generated by Django 2.2.3 on 2020-01-04 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200103_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpu',
            name='boost_clock',
            field=models.FloatField(default=0),
        ),
    ]
