# Generated by Django 2.2.3 on 2020-03-18 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_cpu_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='GPU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tdp', models.IntegerField(default=0)),
                ('benchmark_score', models.IntegerField(verbose_name='b_score')),
                ('clock_speed', models.FloatField(default=0)),
                ('memory_size', models.FloatField(default=0)),
                ('memory_clock', models.FloatField(default=0)),
                ('directx', models.CharField(max_length=100)),
                ('gaming_score', models.FloatField(default=0)),
                ('productivity_score', models.FloatField(default=0)),
                ('blend_score', models.FloatField(default=0)),
                ('value_score', models.FloatField(default=0)),
            ],
        ),
    ]
