# Generated by Django 2.2.3 on 2020-03-18 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_gpu'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpu',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
