# Generated by Django 2.2.3 on 2020-03-18 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_gpu_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpu',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
